//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 02:35:05 PM IST 
//


package com.dhl.xmlpi.shipVal.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Billing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Billing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipperAccountNumber" type="{http://www.dhl.com/datatypes_global}AccountNumber"/>
 *         &lt;element name="ShippingPaymentType" type="{http://www.dhl.com/datatypes_global}ShipmentPaymentType"/>
 *         &lt;element name="BillingAccountNumber" type="{http://www.dhl.com/datatypes_global}AccountNumber" minOccurs="0"/>
 *         &lt;element name="DutyPaymentType" type="{http://www.dhl.com/datatypes_global}DutyTaxPaymentType" minOccurs="0"/>
 *         &lt;element name="DutyAccountNumber" type="{http://www.dhl.com/datatypes_global}AccountNumber" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Billing", propOrder = {
    "shipperAccountNumber",
    "shippingPaymentType",
    "billingAccountNumber",
    "dutyPaymentType",
    "dutyAccountNumber"
})
public class Billing {

    @XmlElement(name = "ShipperAccountNumber", required = true)
    protected String shipperAccountNumber;
    @XmlElement(name = "ShippingPaymentType", required = true)
    protected ShipmentPaymentType shippingPaymentType;
    @XmlElement(name = "BillingAccountNumber")
    protected String billingAccountNumber;
    @XmlElement(name = "DutyPaymentType")
    protected DutyTaxPaymentType dutyPaymentType;
    @XmlElement(name = "DutyAccountNumber")
    protected String dutyAccountNumber;

    /**
     * Gets the value of the shipperAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperAccountNumber() {
        return shipperAccountNumber;
    }

    /**
     * Sets the value of the shipperAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperAccountNumber(String value) {
        this.shipperAccountNumber = value;
    }

    /**
     * Gets the value of the shippingPaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentPaymentType }
     *     
     */
    public ShipmentPaymentType getShippingPaymentType() {
        return shippingPaymentType;
    }

    /**
     * Sets the value of the shippingPaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentPaymentType }
     *     
     */
    public void setShippingPaymentType(ShipmentPaymentType value) {
        this.shippingPaymentType = value;
    }

    /**
     * Gets the value of the billingAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAccountNumber() {
        return billingAccountNumber;
    }

    /**
     * Sets the value of the billingAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAccountNumber(String value) {
        this.billingAccountNumber = value;
    }

    /**
     * Gets the value of the dutyPaymentType property.
     * 
     * @return
     *     possible object is
     *     {@link DutyTaxPaymentType }
     *     
     */
    public DutyTaxPaymentType getDutyPaymentType() {
        return dutyPaymentType;
    }

    /**
     * Sets the value of the dutyPaymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DutyTaxPaymentType }
     *     
     */
    public void setDutyPaymentType(DutyTaxPaymentType value) {
        this.dutyPaymentType = value;
    }

    /**
     * Gets the value of the dutyAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyAccountNumber() {
        return dutyAccountNumber;
    }

    /**
     * Sets the value of the dutyAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyAccountNumber(String value) {
        this.dutyAccountNumber = value;
    }

}
