//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 02:35:05 PM IST 
//

package com.dhl.xmlpi.shipVal.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ExportDeclaration complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ExportDeclaration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InterConsignee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsPartiesRelation" type="{http://www.dhl.com/datatypes_global}YesNo" minOccurs="0"/>
 *         &lt;element name="ECCN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SignatureName" type="{http://www.dhl.com/datatypes_global}SignatureName" minOccurs="0"/>
 *         &lt;element name="SignatureTitle" type="{http://www.dhl.com/datatypes_global}SignatureTitle" minOccurs="0"/>
 *         &lt;element name="ExportReason" type="{http://www.dhl.com/datatypes_global}ExportReason" minOccurs="0"/>
 *         &lt;element name="ExportReasonCode" type="{http://www.dhl.com/datatypes_global}ExportReasonCode" minOccurs="0"/>
 *         &lt;element name="SedNumber" type="{http://www.dhl.com/datatypes_global}SEDNumber" minOccurs="0"/>
 *         &lt;element name="SedNumberType" type="{http://www.dhl.com/datatypes_global}SEDNumberType" minOccurs="0"/>
 *         &lt;element name="MxStateCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExportLineItem" type="{http://www.dhl.com/datatypes_global}ExportLineItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportDeclaration", propOrder = { "interConsignee", "isPartiesRelation", "eccn", "signatureName",
		"signatureTitle", "exportReason", "exportReasonCode", "sedNumber", "sedNumberType", "mxStateCode",
		"invoiceNumber", "invoiceDate", "billToCompanyName", "billToContanctName", "billToAddressLine", "billToCity",
		"billToPostcode", "billToSuburb", "billToState", "billToCountryName", "billToPhoneNumber",
		"billToPhoneNumberExtn", "billToFaxNumber", "billToFederalTaxID", "remarks", "totalSupplCharges",
		"otherCharges1", "otherCharges2", "otherCharges3", "destinationPort", "termsOfPayment", "payerGSTVAT",
		"signatureImage", "receiverReference", "exporterId", "exporterCode", "packageMarks", "otherRemarks2", "otherRemarks3",
		"ruBankINN", "ruBankKPP", "ruBankOKPO", "ruBankOGRN", "ruBankSettlementAcctNumUSDEUR",
		"ruBankSettlementAcctNumRUR", "ruBankName", "addDeclText1", "addDeclText2", "addDeclText3", "exportLineItem" })
public class ExportDeclaration {

	@XmlElement(name = "InterConsignee")
	protected String interConsignee;
	@XmlElement(name = "IsPartiesRelation")
	protected YesNo isPartiesRelation;
	@XmlElement(name = "ECCN")
	protected String eccn;
	@XmlElement(name = "SignatureName")
	protected String signatureName;
	@XmlElement(name = "SignatureTitle")
	protected String signatureTitle;
	@XmlElement(name = "ExportReason")
	protected String exportReason;
	@XmlElement(name = "ExportReasonCode")
	protected ExportReasonCode exportReasonCode;
	@XmlElement(name = "SedNumber")
	protected SEDNumber sedNumber;
	@XmlElement(name = "SedNumberType")
	protected SEDNumberType sedNumberType;
	@XmlElement(name = "MxStateCode")
	protected String mxStateCode;
	@XmlElement(name = "InvoiceNumber", required = true)
	protected String invoiceNumber;
	@XmlElement(name = "InvoiceDate", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar invoiceDate;
	@XmlElement(name = "BillToCompanyName")
	protected String billToCompanyName;
	@XmlElement(name = "BillToContanctName")
	protected String billToContanctName;
	@XmlElement(name = "BillToAddressLine")
	protected List<String> billToAddressLine;
	@XmlElement(name = "BillToCity")
	protected String billToCity;
	@XmlElement(name = "BillToPostcode")
	protected String billToPostcode;
	@XmlElement(name = "BillToSuburb")
	protected String billToSuburb;
	@XmlElement(name = "BillToState")
	protected String billToState;
	@XmlElement(name = "BillToCountryName")
	protected String billToCountryName;
	@XmlElement(name = "BillToPhoneNumber")
	protected String billToPhoneNumber;
	@XmlElement(name = "BillToPhoneNumberExtn")
	protected String billToPhoneNumberExtn;
	@XmlElement(name = "BillToFaxNumber")
	protected String billToFaxNumber;
	@XmlElement(name = "BillToFederalTaxID")
	protected String billToFederalTaxID;
	@XmlElement(name = "Remarks")
	protected String remarks;
	@XmlElement(name = "TotalSupplCharges")
	protected Float totalSupplCharges;
	@XmlElement(name = "OtherCharges1")
	protected Float otherCharges1;
	@XmlElement(name = "OtherCharges2")
	protected Float otherCharges2;
	@XmlElement(name = "OtherCharges3")
	protected Float otherCharges3;
	@XmlElement(name = "DestinationPort")
	protected String destinationPort;
	@XmlElement(name = "TermsOfPayment")
	protected String termsOfPayment;
	@XmlElement(name = "PayerGSTVAT")
	protected String payerGSTVAT;
	@XmlElement(name = "SignatureImage")
	protected byte[] signatureImage;
	@XmlElement(name = "ReceiverReference")
	protected String receiverReference;
	@XmlElement(name = "ExporterId")
	protected String exporterId;
	@XmlElement(name = "ExporterCode")
	protected String exporterCode;
	@XmlElement(name = "PackageMarks")
	protected String packageMarks;
	@XmlElement(name = "OtherRemarks2")
	protected String otherRemarks2;
	@XmlElement(name = "OtherRemarks3")
	protected String otherRemarks3;
	@XmlElement(name = "RUBankINN")
	protected String ruBankINN;
	@XmlElement(name = "RUBankKPP")
	protected String ruBankKPP;
	@XmlElement(name = "RUBankOKPO")
	protected String ruBankOKPO;
	@XmlElement(name = "RUBankOGRN")
	protected String ruBankOGRN;
	@XmlElement(name = "RUBankSettlementAcctNumUSDEUR")
	protected String ruBankSettlementAcctNumUSDEUR;
	@XmlElement(name = "RUBankSettlementAcctNumRUR")
	protected String ruBankSettlementAcctNumRUR;
	@XmlElement(name = "RUBankName")
	protected String ruBankName;
	@XmlElement(name = "AddDeclText1")
	protected String addDeclText1;
	@XmlElement(name = "AddDeclText2")
	protected String addDeclText2;
	@XmlElement(name = "AddDeclText3")
	protected String addDeclText3;
	@XmlElement(name = "ExportLineItem", required = true)
	protected List<ExportLineItem> exportLineItem;

	/**
	 * Gets the value of the interConsignee property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInterConsignee() {
		return interConsignee;
	}

	/**
	 * Sets the value of the interConsignee property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInterConsignee(String value) {
		this.interConsignee = value;
	}

	/**
	 * Gets the value of the isPartiesRelation property.
	 * 
	 * @return possible object is {@link YesNo }
	 * 
	 */
	public YesNo getIsPartiesRelation() {
		return isPartiesRelation;
	}

	/**
	 * Sets the value of the isPartiesRelation property.
	 * 
	 * @param value
	 *            allowed object is {@link YesNo }
	 * 
	 */
	public void setIsPartiesRelation(YesNo value) {
		this.isPartiesRelation = value;
	}

	/**
	 * Gets the value of the eccn property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getECCN() {
		return eccn;
	}

	/**
	 * Sets the value of the eccn property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setECCN(String value) {
		this.eccn = value;
	}

	/**
	 * Gets the value of the signatureName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSignatureName() {
		return signatureName;
	}

	/**
	 * Sets the value of the signatureName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSignatureName(String value) {
		this.signatureName = value;
	}

	/**
	 * Gets the value of the signatureTitle property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSignatureTitle() {
		return signatureTitle;
	}

	/**
	 * Sets the value of the signatureTitle property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSignatureTitle(String value) {
		this.signatureTitle = value;
	}

	/**
	 * Gets the value of the exportReason property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExportReason() {
		return exportReason;
	}

	/**
	 * Sets the value of the exportReason property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExportReason(String value) {
		this.exportReason = value;
	}

	/**
	 * Gets the value of the exportReasonCode property.
	 * 
	 * @return possible object is {@link ExportReasonCode }
	 * 
	 */
	public ExportReasonCode getExportReasonCode() {
		return exportReasonCode;
	}

	/**
	 * Sets the value of the exportReasonCode property.
	 * 
	 * @param value
	 *            allowed object is {@link ExportReasonCode }
	 * 
	 */
	public void setExportReasonCode(ExportReasonCode value) {
		this.exportReasonCode = value;
	}

	/**
	 * Gets the value of the sedNumber property.
	 * 
	 * @return possible object is {@link SEDNumber }
	 * 
	 */
	public SEDNumber getSedNumber() {
		return sedNumber;
	}

	/**
	 * Sets the value of the sedNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link SEDNumber }
	 * 
	 */
	public void setSedNumber(SEDNumber value) {
		this.sedNumber = value;
	}

	/**
	 * Gets the value of the sedNumberType property.
	 * 
	 * @return possible object is {@link SEDNumberType }
	 * 
	 */
	public SEDNumberType getSedNumberType() {
		return sedNumberType;
	}

	/**
	 * Sets the value of the sedNumberType property.
	 * 
	 * @param value
	 *            allowed object is {@link SEDNumberType }
	 * 
	 */
	public void setSedNumberType(SEDNumberType value) {
		this.sedNumberType = value;
	}

	/**
	 * Gets the value of the mxStateCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMxStateCode() {
		return mxStateCode;
	}

	/**
	 * Sets the value of the mxStateCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMxStateCode(String value) {
		this.mxStateCode = value;
	}

	/**
	 * Gets the value of the exportLineItem property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the exportLineItem property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getExportLineItem().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ExportLineItem }
	 * 
	 * 
	 */
	public List<ExportLineItem> getExportLineItem() {
		if (exportLineItem == null) {
			exportLineItem = new ArrayList<ExportLineItem>();
		}
		return this.exportLineItem;
	}

	public String getEccn() {
		return eccn;
	}

	public void setEccn(String eccn) {
		this.eccn = eccn;
	}

	public String getInvoiceNumber() {
		return invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public XMLGregorianCalendar getInvoiceDate() {
		return invoiceDate;
	}

	public void setInvoiceDate(XMLGregorianCalendar invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public String getBillToCompanyName() {
		return billToCompanyName;
	}

	public void setBillToCompanyName(String billToCompanyName) {
		this.billToCompanyName = billToCompanyName;
	}

	public String getBillToContanctName() {
		return billToContanctName;
	}

	public void setBillToContanctName(String billToContanctName) {
		this.billToContanctName = billToContanctName;
	}

	public List<String> getBillToAddressLine() {
        if (billToAddressLine == null) {
        	billToAddressLine = new ArrayList<String>();
        }
        return this.billToAddressLine;
    }

	public String getBillToCity() {
		return billToCity;
	}

	public void setBillToCity(String billToCity) {
		this.billToCity = billToCity;
	}

	public String getBillToPostcode() {
		return billToPostcode;
	}

	public void setBillToPostcode(String billToPostcode) {
		this.billToPostcode = billToPostcode;
	}

	public String getBillToSuburb() {
		return billToSuburb;
	}

	public void setBillToSuburb(String billToSuburb) {
		this.billToSuburb = billToSuburb;
	}

	public String getBillToState() {
		return billToState;
	}

	public void setBillToState(String billToState) {
		this.billToState = billToState;
	}

	public String getBillToCountryName() {
		return billToCountryName;
	}

	public void setBillToCountryName(String billToCountryName) {
		this.billToCountryName = billToCountryName;
	}

	public String getBillToPhoneNumber() {
		return billToPhoneNumber;
	}

	public void setBillToPhoneNumber(String billToPhoneNumber) {
		this.billToPhoneNumber = billToPhoneNumber;
	}

	public String getBillToPhoneNumberExtn() {
		return billToPhoneNumberExtn;
	}

	public void setBillToPhoneNumberExtn(String billToPhoneNumberExtn) {
		this.billToPhoneNumberExtn = billToPhoneNumberExtn;
	}

	public String getBillToFaxNumber() {
		return billToFaxNumber;
	}

	public void setBillToFaxNumber(String billToFaxNumber) {
		this.billToFaxNumber = billToFaxNumber;
	}

	public String getBillToFederalTaxID() {
		return billToFederalTaxID;
	}

	public void setBillToFederalTaxID(String billToFederalTaxID) {
		this.billToFederalTaxID = billToFederalTaxID;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Float getTotalSupplCharges() {
		return totalSupplCharges;
	}

	public void setTotalSupplCharges(Float totalSupplCharges) {
		this.totalSupplCharges = totalSupplCharges;
	}

	public Float getOtherCharges1() {
		return otherCharges1;
	}

	public void setOtherCharges1(Float otherCharges1) {
		this.otherCharges1 = otherCharges1;
	}

	public Float getOtherCharges2() {
		return otherCharges2;
	}

	public void setOtherCharges2(Float otherCharges2) {
		this.otherCharges2 = otherCharges2;
	}

	public Float getOtherCharges3() {
		return otherCharges3;
	}

	public void setOtherCharges3(Float otherCharges3) {
		this.otherCharges3 = otherCharges3;
	}

	public String getDestinationPort() {
		return destinationPort;
	}

	public void setDestinationPort(String destinationPort) {
		this.destinationPort = destinationPort;
	}

	public String getTermsOfPayment() {
		return termsOfPayment;
	}

	public void setTermsOfPayment(String termsOfPayment) {
		this.termsOfPayment = termsOfPayment;
	}

	public String getPayerGSTVAT() {
		return payerGSTVAT;
	}

	public void setPayerGSTVAT(String payerGSTVAT) {
		this.payerGSTVAT = payerGSTVAT;
	}

	public byte[] getSignatureImage() {
		return signatureImage;
	}

	public void setSignatureImage(byte[] signatureImage) {
		this.signatureImage = signatureImage;
	}

	public String getReceiverReference() {
		return receiverReference;
	}

	public void setReceiverReference(String receiverReference) {
		this.receiverReference = receiverReference;
	}
	
	public String getExporterId() {
		return exporterId;
	}

	public void setExporterId(String exporterId) {
		this.exporterId = exporterId;
	}

	public String getExporterCode() {
		return exporterCode;
	}

	public void setExporterCode(String exporterCode) {
		this.exporterCode = exporterCode;
	}

	public String getPackageMarks() {
		return packageMarks;
	}

	public void setPackageMarks(String packageMarks) {
		this.packageMarks = packageMarks;
	}

	public String getOtherRemarks2() {
		return otherRemarks2;
	}

	public void setOtherRemarks2(String otherRemarks2) {
		this.otherRemarks2 = otherRemarks2;
	}

	public String getOtherRemarks3() {
		return otherRemarks3;
	}

	public void setOtherRemarks3(String otherRemarks3) {
		this.otherRemarks3 = otherRemarks3;
	}

	public String getRuBankINN() {
		return ruBankINN;
	}

	public void setRuBankINN(String ruBankINN) {
		this.ruBankINN = ruBankINN;
	}

	public String getRuBankKPP() {
		return ruBankKPP;
	}

	public void setRuBankKPP(String ruBankKPP) {
		this.ruBankKPP = ruBankKPP;
	}

	public String getRuBankOKPO() {
		return ruBankOKPO;
	}

	public void setRuBankOKPO(String ruBankOKPO) {
		this.ruBankOKPO = ruBankOKPO;
	}

	public String getRuBankOGRN() {
		return ruBankOGRN;
	}

	public void setRuBankOGRN(String ruBankOGRN) {
		this.ruBankOGRN = ruBankOGRN;
	}

	public String getRuBankSettlementAcctNumUSDEUR() {
		return ruBankSettlementAcctNumUSDEUR;
	}

	public void setRuBankSettlementAcctNumUSDEUR(String ruBankSettlementAcctNumUSDEUR) {
		this.ruBankSettlementAcctNumUSDEUR = ruBankSettlementAcctNumUSDEUR;
	}

	public String getRuBankSettlementAcctNumRUR() {
		return ruBankSettlementAcctNumRUR;
	}

	public void setRuBankSettlementAcctNumRUR(String ruBankSettlementAcctNumRUR) {
		this.ruBankSettlementAcctNumRUR = ruBankSettlementAcctNumRUR;
	}

	public String getRuBankName() {
		return ruBankName;
	}

	public void setRuBankName(String ruBankName) {
		this.ruBankName = ruBankName;
	}

	public String getAddDeclText1() {
		return addDeclText1;
	}

	public void setAddDeclText1(String addDeclText1) {
		this.addDeclText1 = addDeclText1;
	}

	public String getAddDeclText2() {
		return addDeclText2;
	}

	public void setAddDeclText2(String addDeclText2) {
		this.addDeclText2 = addDeclText2;
	}

	public String getAddDeclText3() {
		return addDeclText3;
	}

	public void setAddDeclText3(String addDeclText3) {
		this.addDeclText3 = addDeclText3;
	}
}
