//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 02:35:05 PM IST 
//


package com.dhl.xmlpi.shipVal.models;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.dhl.xmlpi.labelservice.model.datatypes.Piece;


/**
 * LabelImage
 * 
 * <p>Java class for LabelImage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelImage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OutputFormat" type="{http://www.dhl.com/datatypes_global}OutputFormat" minOccurs="0"/>
 *         &lt;element name="OutputImage" type="{http://www.dhl.com/datatypes_global}OutputImage" minOccurs="0"/>
 *         &lt;element name="MultiLabels" type="{http://www.dhl.com/datatypes_global}MultiLabels" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelImage", propOrder = {
    "outputFormat",
    "outputImage",
    "multiLabels"
})
public class LabelImage {

    @XmlElement(name = "OutputFormat")
    protected OutputFormat outputFormat;
    @XmlElement(name = "OutputImage")
    protected byte[] outputImage;
    
    //BEGIN :: Added below new implementation for decoding Multiple Images :: Rajesh Nagampurath :: 15-MAY-2015 | Shipment Receipt CR | XML_PI_v52_Cyrillic_ShpRcpt
    @XmlElement(name = "MultiLabels")
    protected MultiLabels multiLabels;
    
	/**
	 * @return the multiLabels
	 */
	public MultiLabels getMultiLabels() {
		return multiLabels;
	}

	/**
	 * @param multiLabels the multiLabels to set
	 */
	public void setMultiLabels(MultiLabels multiLabels) {
		this.multiLabels = multiLabels;
	}
	//END :: Rajesh Nagampurath :: 15-MAY-2015 | XMLPI Shipment Receipt CR | XML_PI_v52_Cyrillic_ShpRcpt
	
	/**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link OutputFormat }
     *     
     */
    public OutputFormat getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputFormat }
     *     
     */
    public void setOutputFormat(OutputFormat value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the outputImage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getOutputImage() {
        return outputImage;
    }

    /**
     * Sets the value of the outputImage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setOutputImage(byte[] value) {
        this.outputImage = ((byte[]) value);
    }

}
