//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 02:35:05 PM IST 
//


package com.dhl.xmlpi.shipVal.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Place complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Place">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResidenceOrBusiness" type="{http://www.dhl.com/datatypes_global}ResidenceOrBusiness" minOccurs="0"/>
 *         &lt;element name="CompanyName" type="{http://www.dhl.com/datatypes_global}CompanyNameValidator" minOccurs="0"/>
 *         &lt;element name="AddressLine" type="{http://www.dhl.com/datatypes_global}AddressLine" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.dhl.com/datatypes_global}City"/>
 *         &lt;element name="CountryCode" type="{http://www.dhl.com/datatypes_global}CountryCode"/>
 *         &lt;element name="DivisionCode" type="{http://www.dhl.com/datatypes_global}StateCode" minOccurs="0"/>
 *         &lt;element name="Division" type="{http://www.dhl.com/datatypes_global}State" minOccurs="0"/>
 *         &lt;element name="PostalCode" type="{http://www.dhl.com/datatypes_global}PostalCode" minOccurs="0"/>
 *         &lt;element name="PackageLocation" type="{http://www.dhl.com/datatypes_global}PackageLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Place", propOrder = {
    "residenceOrBusiness",
    "companyName",
    "addressLine",
    "city",
    "countryCode",
    "divisionCode",
    "division",
    "postalCode",
    "packageLocation"
})
public class Place {

    @XmlElement(name = "ResidenceOrBusiness")
    protected ResidenceOrBusiness residenceOrBusiness;
    @XmlElement(name = "CompanyName")
    protected String companyName;
    @XmlElement(name = "AddressLine")
    protected String addressLine;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "DivisionCode")
    protected String divisionCode;
    @XmlElement(name = "Division")
    protected String division;
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    @XmlElement(name = "PackageLocation")
    protected String packageLocation;

    /**
     * Gets the value of the residenceOrBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link ResidenceOrBusiness }
     *     
     */
    public ResidenceOrBusiness getResidenceOrBusiness() {
        return residenceOrBusiness;
    }

    /**
     * Sets the value of the residenceOrBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResidenceOrBusiness }
     *     
     */
    public void setResidenceOrBusiness(ResidenceOrBusiness value) {
        this.residenceOrBusiness = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the addressLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine() {
        return addressLine;
    }

    /**
     * Sets the value of the addressLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine(String value) {
        this.addressLine = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the divisionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisionCode() {
        return divisionCode;
    }

    /**
     * Sets the value of the divisionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisionCode(String value) {
        this.divisionCode = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the packageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageLocation() {
        return packageLocation;
    }

    /**
     * Sets the value of the packageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageLocation(String value) {
        this.packageLocation = value;
    }

}
