//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 10:21:23 AM IST 
//


package com.dhl.xmlpi.labelservice.model.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response" type="{http://www.dhl.com/LabelService_datatypes}Response"/>
 *         &lt;element name="Note" type="{http://www.dhl.com/LabelService_datatypes}Note" minOccurs="0"/>
 *         &lt;element name="AirwayBillNumber" type="{http://www.dhl.com/LabelService_datatypes}AirwayBillNumber"/>
 *         &lt;element name="LabelType" type="{http://www.dhl.com/LabelService_datatypes}LabelType"/>
 *         &lt;element name="LabelPrintCommands" type="{http://www.dhl.com/LabelService_datatypes}LabelPrintCommands" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "note",
    "airwayBillNumber",
    "labelType",
    "labelPrintCommands"
})
@XmlRootElement(name = "LabelResponse", namespace = "http://www.dhl.com")
public class LabelResponse {

    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElement(name = "Note")
    protected Note note;
    @XmlElement(name = "AirwayBillNumber", required = true)
    protected String airwayBillNumber;
    @XmlElement(name = "LabelType", required = true)
    protected LabelType labelType;
    @XmlElement(name = "LabelPrintCommands")
    protected List<LabelPrintCommands> labelPrintCommands;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Note }
     *     
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Note }
     *     
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the airwayBillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwayBillNumber() {
        return airwayBillNumber;
    }

    /**
     * Sets the value of the airwayBillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwayBillNumber(String value) {
        this.airwayBillNumber = value;
    }

    /**
     * Gets the value of the labelType property.
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getLabelType() {
        return labelType;
    }

    /**
     * Sets the value of the labelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setLabelType(LabelType value) {
        this.labelType = value;
    }

    /**
     * Gets the value of the labelPrintCommands property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelPrintCommands property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelPrintCommands().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelPrintCommands }
     * 
     * 
     */
    public List<LabelPrintCommands> getLabelPrintCommands() {
        if (labelPrintCommands == null) {
            labelPrintCommands = new ArrayList<LabelPrintCommands>();
        }
        return this.labelPrintCommands;
    }

}
