//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.04 at 10:21:23 AM IST 
//


package com.dhl.xmlpi.labelservice.model.response;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Shipment
 * 
 * <p>Java class for Shipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Shipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductContentCode" type="{http://www.dhl.com/LabelService_datatypes}ProductContentCode" minOccurs="0"/>
 *         &lt;element name="LocalProductCode" type="{http://www.dhl.com/LabelService_datatypes}LocalProductCode" minOccurs="0"/>
 *         &lt;element name="GlobalProductCode" type="{http://www.dhl.com/LabelService_datatypes}GlobalProductCode" minOccurs="0"/>
 *         &lt;element name="ProductName" type="{http://www.dhl.com/LabelService_datatypes}ProductName" minOccurs="0"/>
 *         &lt;element name="ProductSortCode" type="{http://www.dhl.com/LabelService_datatypes}ProductSortCode" minOccurs="0"/>
 *         &lt;element name="InverseVideoInd" type="{http://www.dhl.com/LabelService_datatypes}InverseVideoInd" minOccurs="0"/>
 *         &lt;element name="ShptCalendarDate" type="{http://www.dhl.com/LabelService_datatypes}ShptCalendarDate" minOccurs="0"/>
 *         &lt;element name="AutosortSvcDateCode" type="{http://www.dhl.com/LabelService_datatypes}AutosortSvcDateCode" minOccurs="0"/>
 *         &lt;element name="AutosortSvcTimeCode" type="{http://www.dhl.com/LabelService_datatypes}AutosortSvcTimeCode" minOccurs="0"/>
 *         &lt;element name="WeightUOM" type="{http://www.dhl.com/LabelService_datatypes}WeightUOM"/>
 *         &lt;element name="Weight" type="{http://www.dhl.com/LabelService_datatypes}Weight"/>
 *         &lt;element name="DimensionalWeight" type="{http://www.dhl.com/LabelService_datatypes}DimensionalWeight" minOccurs="0"/>
 *         &lt;element name="ShipmentContents" type="{http://www.dhl.com/LabelService_datatypes}ShipmentContents" minOccurs="0"/>
 *         &lt;element name="TotalNumOfPcs" type="{http://www.dhl.com/LabelService_datatypes}TotalNumOfPcs"/>
 *         &lt;element name="PickupDate" type="{http://www.dhl.com/LabelService_datatypes}PickupDate"/>
 *         &lt;element name="FreightAcctNum" type="{http://www.dhl.com/LabelService_datatypes}FreightAcctNum" minOccurs="0"/>
 *         &lt;element name="DutySvcIndicator" type="{http://www.dhl.com/LabelService_datatypes}DutySvcIndicator" minOccurs="0"/>
 *         &lt;element name="DutyAcctNum" type="{http://www.dhl.com/LabelService_datatypes}DutyAcctNum" minOccurs="0"/>
 *         &lt;element name="TaxAcctNum" type="{http://www.dhl.com/LabelService_datatypes}TaxAcctNum" minOccurs="0"/>
 *         &lt;element name="ShptInfo1" type="{http://www.dhl.com/LabelService_datatypes}ShptInfo1" minOccurs="0"/>
 *         &lt;element name="ShptInfo2" type="{http://www.dhl.com/LabelService_datatypes}ShptInfo2" minOccurs="0"/>
 *         &lt;element name="ShptInfo3" type="{http://www.dhl.com/LabelService_datatypes}ShptInfo3" minOccurs="0"/>
 *         &lt;element name="PaymentCode" type="{http://www.dhl.com/LabelService_datatypes}PaymentCode" minOccurs="0"/>
 *         &lt;element name="CustData" type="{http://www.dhl.com/LabelService_datatypes}CustData" minOccurs="0"/>
 *         &lt;element name="RouteLcSpcCode" type="{http://www.dhl.com/LabelService_datatypes}RouteLcSpcCode" minOccurs="0"/>
 *         &lt;element name="RoutingTextCode" type="{http://www.dhl.com/LabelService_datatypes}RoutingTextCode" minOccurs="0"/>
 *         &lt;element name="OutboundSortCode" type="{http://www.dhl.com/LabelService_datatypes}OutboundSortCode" minOccurs="0"/>
 *         &lt;element name="InboundSortCode" type="{http://www.dhl.com/LabelService_datatypes}InboundSortCode" minOccurs="0"/>
 *         &lt;element name="DeliveryDay" type="{http://www.dhl.com/LabelService_datatypes}DeliveryDay" minOccurs="0"/>
 *         &lt;element name="DeliveryTime" type="{http://www.dhl.com/LabelService_datatypes}DeliveryTime" minOccurs="0"/>
 *         &lt;element name="SpclInfo1" type="{http://www.dhl.com/LabelService_datatypes}SpclInfo1" minOccurs="0"/>
 *         &lt;element name="SpclInfo2" type="{http://www.dhl.com/LabelService_datatypes}SpclInfo2" minOccurs="0"/>
 *         &lt;element name="SpclInfo3" type="{http://www.dhl.com/LabelService_datatypes}SpclInfo3" minOccurs="0"/>
 *         &lt;element name="SpclInfoCmb" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoCmb" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide1" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide1" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide2" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide2" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide3" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide3" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide4" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide4" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide5" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide5" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide6" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide6" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide7" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide7" minOccurs="0"/>
 *         &lt;element name="SpclInfoSide8" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSide8" minOccurs="0"/>
 *         &lt;element name="SpclInfoSideCmb" type="{http://www.dhl.com/LabelService_datatypes}SpclInfoSideCmb" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shipment", propOrder = {
    "productContentCode",
    "localProductCode",
    "globalProductCode",
    "productName",
    "productSortCode",
    "inverseVideoInd",
    "shptCalendarDate",
    "autosortSvcDateCode",
    "autosortSvcTimeCode",
    "weightUOM",
    "weight",
    "dimensionalWeight",
    "shipmentContents",
    "totalNumOfPcs",
    "pickupDate",
    "freightAcctNum",
    "dutySvcIndicator",
    "dutyAcctNum",
    "taxAcctNum",
    "shptInfo1",
    "shptInfo2",
    "shptInfo3",
    "paymentCode",
    "custData",
    "routeLcSpcCode",
    "routingTextCode",
    "outboundSortCode",
    "inboundSortCode",
    "deliveryDay",
    "deliveryTime",
    "spclInfo1",
    "spclInfo2",
    "spclInfo3",
    "spclInfoCmb",
    "spclInfoSide1",
    "spclInfoSide2",
    "spclInfoSide3",
    "spclInfoSide4",
    "spclInfoSide5",
    "spclInfoSide6",
    "spclInfoSide7",
    "spclInfoSide8",
    "spclInfoSideCmb"
})
public class Shipment {

    @XmlElement(name = "ProductContentCode")
    protected String productContentCode;
    @XmlElement(name = "LocalProductCode")
    protected String localProductCode;
    @XmlElement(name = "GlobalProductCode")
    protected String globalProductCode;
    @XmlElement(name = "ProductName")
    protected String productName;
    @XmlElement(name = "ProductSortCode")
    protected String productSortCode;
    @XmlElement(name = "InverseVideoInd")
    protected InverseVideoInd inverseVideoInd;
    @XmlElement(name = "ShptCalendarDate")
    protected XMLGregorianCalendar shptCalendarDate;
    @XmlElement(name = "AutosortSvcDateCode")
    protected String autosortSvcDateCode;
    @XmlElement(name = "AutosortSvcTimeCode")
    protected String autosortSvcTimeCode;
    @XmlElement(name = "WeightUOM", required = true)
    protected WeightUOM weightUOM;
    @XmlElement(name = "Weight", required = true)
    protected BigDecimal weight;
    //BEGIN :: Added below to populate DimWeight on the RU template label :: Rajesh Nagampurath :: 22-JAN-2015 | XMLPI Label Enhancement | XML_PI_v52_Cyrillic
    @XmlElement(name = "DimensionalWeight")
    protected BigDecimal dimensionalWeight;
    //END
    @XmlElement(name = "ShipmentContents")
    protected String shipmentContents;
    @XmlElement(name = "TotalNumOfPcs", required = true)
    protected BigInteger totalNumOfPcs;
    @XmlElement(name = "PickupDate", required = true)
    protected XMLGregorianCalendar pickupDate;
    @XmlElement(name = "FreightAcctNum")
    protected String freightAcctNum;
    @XmlElement(name = "DutySvcIndicator")
    protected String dutySvcIndicator;
    @XmlElement(name = "DutyAcctNum")
    protected String dutyAcctNum;
    @XmlElement(name = "TaxAcctNum")
    protected String taxAcctNum;
    @XmlElement(name = "ShptInfo1")
    protected String shptInfo1;
    @XmlElement(name = "ShptInfo2")
    protected String shptInfo2;
    @XmlElement(name = "ShptInfo3")
    protected String shptInfo3;
    @XmlElement(name = "PaymentCode")
    protected PaymentCode paymentCode;
    @XmlElement(name = "CustData")
    protected String custData;
    @XmlElement(name = "RouteLcSpcCode")
    protected String routeLcSpcCode;
    @XmlElement(name = "RoutingTextCode")
    protected String routingTextCode;
    @XmlElement(name = "OutboundSortCode")
    protected String outboundSortCode;
    @XmlElement(name = "InboundSortCode")
    protected String inboundSortCode;
    @XmlElement(name = "DeliveryDay")
    protected String deliveryDay;
    @XmlElement(name = "DeliveryTime")
    protected String deliveryTime;
    @XmlElement(name = "SpclInfo1")
    protected String spclInfo1;
    @XmlElement(name = "SpclInfo2")
    protected String spclInfo2;
    @XmlElement(name = "SpclInfo3")
    protected String spclInfo3;
    @XmlElement(name = "SpclInfoCmb")
    protected String spclInfoCmb;
    @XmlElement(name = "SpclInfoSide1")
    protected String spclInfoSide1;
    @XmlElement(name = "SpclInfoSide2")
    protected String spclInfoSide2;
    @XmlElement(name = "SpclInfoSide3")
    protected String spclInfoSide3;
    @XmlElement(name = "SpclInfoSide4")
    protected String spclInfoSide4;
    @XmlElement(name = "SpclInfoSide5")
    protected String spclInfoSide5;
    @XmlElement(name = "SpclInfoSide6")
    protected String spclInfoSide6;
    @XmlElement(name = "SpclInfoSide7")
    protected String spclInfoSide7;
    @XmlElement(name = "SpclInfoSide8")
    protected String spclInfoSide8;
    @XmlElement(name = "SpclInfoSideCmb")
    protected String spclInfoSideCmb;

    /**
     * Gets the value of the productContentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductContentCode() {
        return productContentCode;
    }

    /**
     * Sets the value of the productContentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductContentCode(String value) {
        this.productContentCode = value;
    }

    /**
     * Gets the value of the localProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalProductCode() {
        return localProductCode;
    }

    /**
     * Sets the value of the localProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalProductCode(String value) {
        this.localProductCode = value;
    }

    /**
     * Gets the value of the globalProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalProductCode() {
        return globalProductCode;
    }

    /**
     * Sets the value of the globalProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalProductCode(String value) {
        this.globalProductCode = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSortCode() {
        return productSortCode;
    }

    /**
     * Sets the value of the productSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSortCode(String value) {
        this.productSortCode = value;
    }

    /**
     * Gets the value of the inverseVideoInd property.
     * 
     * @return
     *     possible object is
     *     {@link InverseVideoInd }
     *     
     */
    public InverseVideoInd getInverseVideoInd() {
        return inverseVideoInd;
    }

    /**
     * Sets the value of the inverseVideoInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link InverseVideoInd }
     *     
     */
    public void setInverseVideoInd(InverseVideoInd value) {
        this.inverseVideoInd = value;
    }

    /**
     * Gets the value of the shptCalendarDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShptCalendarDate() {
        return shptCalendarDate;
    }

    /**
     * Sets the value of the shptCalendarDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShptCalendarDate(XMLGregorianCalendar value) {
        this.shptCalendarDate = value;
    }

    /**
     * Gets the value of the autosortSvcDateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutosortSvcDateCode() {
        return autosortSvcDateCode;
    }

    /**
     * Sets the value of the autosortSvcDateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutosortSvcDateCode(String value) {
        this.autosortSvcDateCode = value;
    }

    /**
     * Gets the value of the autosortSvcTimeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutosortSvcTimeCode() {
        return autosortSvcTimeCode;
    }

    /**
     * Sets the value of the autosortSvcTimeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutosortSvcTimeCode(String value) {
        this.autosortSvcTimeCode = value;
    }

    /**
     * Gets the value of the weightUOM property.
     * 
     * @return
     *     possible object is
     *     {@link WeightUOM }
     *     
     */
    public WeightUOM getWeightUOM() {
        return weightUOM;
    }

    /**
     * Sets the value of the weightUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightUOM }
     *     
     */
    public void setWeightUOM(WeightUOM value) {
        this.weightUOM = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    
    /**
     * Gets the value of the shipmentContents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentContents() {
        return shipmentContents;
    }

    /**
     * Sets the value of the shipmentContents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentContents(String value) {
        this.shipmentContents = value;
    }

    /**
     * Gets the value of the totalNumOfPcs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNumOfPcs() {
        return totalNumOfPcs;
    }

    /**
     * Sets the value of the totalNumOfPcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNumOfPcs(BigInteger value) {
        this.totalNumOfPcs = value;
    }

    /**
     * Gets the value of the pickupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPickupDate() {
        return pickupDate;
    }

    /**
     * Sets the value of the pickupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPickupDate(XMLGregorianCalendar value) {
        this.pickupDate = value;
    }

    /**
     * Gets the value of the freightAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightAcctNum() {
        return freightAcctNum;
    }

    /**
     * Sets the value of the freightAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightAcctNum(String value) {
        this.freightAcctNum = value;
    }

    /**
     * Gets the value of the dutySvcIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutySvcIndicator() {
        return dutySvcIndicator;
    }

    /**
     * Sets the value of the dutySvcIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutySvcIndicator(String value) {
        this.dutySvcIndicator = value;
    }

    /**
     * Gets the value of the dutyAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyAcctNum() {
        return dutyAcctNum;
    }

    /**
     * Sets the value of the dutyAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyAcctNum(String value) {
        this.dutyAcctNum = value;
    }

    /**
     * Gets the value of the taxAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAcctNum() {
        return taxAcctNum;
    }

    /**
     * Sets the value of the taxAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAcctNum(String value) {
        this.taxAcctNum = value;
    }

    /**
     * Gets the value of the shptInfo1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShptInfo1() {
        return shptInfo1;
    }

    /**
     * Sets the value of the shptInfo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShptInfo1(String value) {
        this.shptInfo1 = value;
    }

    /**
     * Gets the value of the shptInfo2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShptInfo2() {
        return shptInfo2;
    }

    /**
     * Sets the value of the shptInfo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShptInfo2(String value) {
        this.shptInfo2 = value;
    }

    /**
     * Gets the value of the shptInfo3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShptInfo3() {
        return shptInfo3;
    }

    /**
     * Sets the value of the shptInfo3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShptInfo3(String value) {
        this.shptInfo3 = value;
    }

    /**
     * Gets the value of the paymentCode property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCode }
     *     
     */
    public PaymentCode getPaymentCode() {
        return paymentCode;
    }

    /**
     * Sets the value of the paymentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCode }
     *     
     */
    public void setPaymentCode(PaymentCode value) {
        this.paymentCode = value;
    }

    /**
     * Gets the value of the custData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustData() {
        return custData;
    }

    /**
     * Sets the value of the custData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustData(String value) {
        this.custData = value;
    }

    /**
     * Gets the value of the routeLcSpcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteLcSpcCode() {
        return routeLcSpcCode;
    }

    /**
     * Sets the value of the routeLcSpcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteLcSpcCode(String value) {
        this.routeLcSpcCode = value;
    }

    /**
     * Gets the value of the routingTextCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingTextCode() {
        return routingTextCode;
    }

    /**
     * Sets the value of the routingTextCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingTextCode(String value) {
        this.routingTextCode = value;
    }

    /**
     * Gets the value of the outboundSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutboundSortCode() {
        return outboundSortCode;
    }

    /**
     * Sets the value of the outboundSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutboundSortCode(String value) {
        this.outboundSortCode = value;
    }

    /**
     * Gets the value of the inboundSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInboundSortCode() {
        return inboundSortCode;
    }

    /**
     * Sets the value of the inboundSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInboundSortCode(String value) {
        this.inboundSortCode = value;
    }

    /**
     * Gets the value of the deliveryDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDay() {
        return deliveryDay;
    }

    /**
     * Sets the value of the deliveryDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDay(String value) {
        this.deliveryDay = value;
    }

    /**
     * Gets the value of the deliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * Sets the value of the deliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTime(String value) {
        this.deliveryTime = value;
    }

    /**
     * Gets the value of the spclInfo1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfo1() {
        return spclInfo1;
    }

    /**
     * Sets the value of the spclInfo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfo1(String value) {
        this.spclInfo1 = value;
    }

    /**
     * Gets the value of the spclInfo2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfo2() {
        return spclInfo2;
    }

    /**
     * Sets the value of the spclInfo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfo2(String value) {
        this.spclInfo2 = value;
    }

    /**
     * Gets the value of the spclInfo3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfo3() {
        return spclInfo3;
    }

    /**
     * Sets the value of the spclInfo3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfo3(String value) {
        this.spclInfo3 = value;
    }

    /**
     * Gets the value of the spclInfoCmb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoCmb() {
        return spclInfoCmb;
    }

    /**
     * Sets the value of the spclInfoCmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoCmb(String value) {
        this.spclInfoCmb = value;
    }

    /**
     * Gets the value of the spclInfoSide1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide1() {
        return spclInfoSide1;
    }

    /**
     * Sets the value of the spclInfoSide1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide1(String value) {
        this.spclInfoSide1 = value;
    }

    /**
     * Gets the value of the spclInfoSide2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide2() {
        return spclInfoSide2;
    }

    /**
     * Sets the value of the spclInfoSide2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide2(String value) {
        this.spclInfoSide2 = value;
    }

    /**
     * Gets the value of the spclInfoSide3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide3() {
        return spclInfoSide3;
    }

    /**
     * Sets the value of the spclInfoSide3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide3(String value) {
        this.spclInfoSide3 = value;
    }

    /**
     * Gets the value of the spclInfoSide4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide4() {
        return spclInfoSide4;
    }

    /**
     * Sets the value of the spclInfoSide4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide4(String value) {
        this.spclInfoSide4 = value;
    }

    /**
     * Gets the value of the spclInfoSide5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide5() {
        return spclInfoSide5;
    }

    /**
     * Sets the value of the spclInfoSide5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide5(String value) {
        this.spclInfoSide5 = value;
    }

    /**
     * Gets the value of the spclInfoSide6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide6() {
        return spclInfoSide6;
    }

    /**
     * Sets the value of the spclInfoSide6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide6(String value) {
        this.spclInfoSide6 = value;
    }

    /**
     * Gets the value of the spclInfoSide7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide7() {
        return spclInfoSide7;
    }

    /**
     * Sets the value of the spclInfoSide7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide7(String value) {
        this.spclInfoSide7 = value;
    }

    /**
     * Gets the value of the spclInfoSide8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSide8() {
        return spclInfoSide8;
    }

    /**
     * Sets the value of the spclInfoSide8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSide8(String value) {
        this.spclInfoSide8 = value;
    }

    /**
   	 * @return the dimensionalWeight
   	 */
   	public BigDecimal getDimensionalWeight() {
   		return dimensionalWeight;
   	}

   	/**
   	 * @param dimensionalWeight the dimensionalWeight to set
   	 */
   	public void setDimensionalWeight(BigDecimal dimensionalWeight) {
   		this.dimensionalWeight = dimensionalWeight;
   	}
    /**
     * Gets the value of the spclInfoSideCmb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpclInfoSideCmb() {
        return spclInfoSideCmb;
    }

    /**
     * Sets the value of the spclInfoSideCmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpclInfoSideCmb(String value) {
        this.spclInfoSideCmb = value;
    }

}
