//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.25 at 02:04:03 PM IST 
//


package com.dhl.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ShipmentInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginServiceArea" type="{http://www.dhl.com/datatypes}OriginServiceArea"/>
 *         &lt;element name="DestinationServiceArea" type="{http://www.dhl.com/datatypes}DestinationServiceArea"/>
 *         &lt;element name="ShipperName" type="{http://www.dhl.com/datatypes}PersonName"/>
 *         &lt;element name="ShipperAccountNumber" type="{http://www.dhl.com/datatypes}AccountNumber" minOccurs="0"/>
 *         &lt;element name="ConsigneeName" type="{http://www.dhl.com/datatypes}PersonName"/>
 *         &lt;element name="ShipmentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Pieces" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WeightUnit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="L"/>
 *               &lt;enumeration value="K"/>
 *               &lt;enumeration value="G"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="ShipmentEvent" type="{http://www.dhl.com/datatypes}ShipmentEvent" maxOccurs="unbounded"/>
 *           &lt;element name="ShipperReference" type="{http://www.dhl.com/datatypes}Reference"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentInfo", propOrder = {
    "originServiceArea",
    "destinationServiceArea",
    "shipperName",
    "shipperAccountNumber",
    "consigneeName",
    "shipmentDate",
    "pieces",
    "weight",
    "weightUnit",
    "shipmentEvent",
    "shipperReference"
})
public class ShipmentInfo {

    @XmlElement(name = "OriginServiceArea", required = true)
    protected OriginServiceArea originServiceArea;
    @XmlElement(name = "DestinationServiceArea", required = true)
    protected DestinationServiceArea destinationServiceArea;
    @XmlElement(name = "ShipperName", required = true)
    protected String shipperName;
    @XmlElement(name = "ShipperAccountNumber")
    protected Long shipperAccountNumber;
    @XmlElement(name = "ConsigneeName", required = true)
    protected String consigneeName;
    @XmlElement(name = "ShipmentDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar shipmentDate;
    @XmlElement(name = "Pieces")
    protected Object pieces;
    @XmlElement(name = "Weight")
    protected String weight;
    @XmlElement(name = "WeightUnit")
    protected String weightUnit;
    @XmlElement(name = "ShipmentEvent")
    protected List<ShipmentEvent> shipmentEvent;
    @XmlElement(name = "ShipperReference")
    protected Reference shipperReference;

    /**
     * Gets the value of the originServiceArea property.
     * 
     * @return
     *     possible object is
     *     {@link OriginServiceArea }
     *     
     */
    public OriginServiceArea getOriginServiceArea() {
        return originServiceArea;
    }

    /**
     * Sets the value of the originServiceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginServiceArea }
     *     
     */
    public void setOriginServiceArea(OriginServiceArea value) {
        this.originServiceArea = value;
    }

    /**
     * Gets the value of the destinationServiceArea property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationServiceArea }
     *     
     */
    public DestinationServiceArea getDestinationServiceArea() {
        return destinationServiceArea;
    }

    /**
     * Sets the value of the destinationServiceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationServiceArea }
     *     
     */
    public void setDestinationServiceArea(DestinationServiceArea value) {
        this.destinationServiceArea = value;
    }

    /**
     * Gets the value of the shipperName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperName() {
        return shipperName;
    }

    /**
     * Sets the value of the shipperName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperName(String value) {
        this.shipperName = value;
    }

    /**
     * Gets the value of the shipperAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getShipperAccountNumber() {
        return shipperAccountNumber;
    }

    /**
     * Sets the value of the shipperAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setShipperAccountNumber(Long value) {
        this.shipperAccountNumber = value;
    }

    /**
     * Gets the value of the consigneeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * Sets the value of the consigneeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeName(String value) {
        this.consigneeName = value;
    }

    /**
     * Gets the value of the shipmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShipmentDate() {
        return shipmentDate;
    }

    /**
     * Sets the value of the shipmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShipmentDate(XMLGregorianCalendar value) {
        this.shipmentDate = value;
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPieces() {
        return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPieces(Object value) {
        this.pieces = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeight(String value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightUnit() {
        return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightUnit(String value) {
        this.weightUnit = value;
    }

    /**
     * Gets the value of the shipmentEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipmentEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipmentEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShipmentEvent }
     * 
     * 
     */
    public List<ShipmentEvent> getShipmentEvent() {
        if (shipmentEvent == null) {
            shipmentEvent = new ArrayList<ShipmentEvent>();
        }
        return this.shipmentEvent;
    }

    /**
     * Gets the value of the shipperReference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getShipperReference() {
        return shipperReference;
    }

    /**
     * Sets the value of the shipperReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setShipperReference(Reference value) {
        this.shipperReference = value;
    }

}
