//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:27 PM IST 
//


package com.dhl.xmlpi.labelservice.model.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArchiveLabelTemplate.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ArchiveLabelTemplate">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="30"/>
 *     &lt;enumeration value="ARCH_8X4_A4_PDF"/>
 *     &lt;enumeration value="ARCH_8X4_thermal"/>
 *     &lt;enumeration value="ARCH_8X4_A4_TC_PDF"/>
 *     &lt;enumeration value="ARCH_6X4_thermal"/>
 *     &lt;enumeration value="ARCH_6X4_A4_PDF"/>
 *     &lt;enumeration value="ARCH_8X4_CI_PDF"/>
 *     &lt;enumeration value="ARCH_8X4_CI_thermal"/>
 *     &lt;enumeration value="ARCH_8X4_RU_A4_PDF"/>
 *     &lt;enumeration value="ARCH_6X4_PDF"/>
 *     &lt;enumeration value="ARCH_8X4_PDF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ArchiveLabelTemplate")
@XmlEnum
public enum ArchiveLabelTemplate {

	// 2014 July 07, Victor changing A4 Archive template to ARCH_8X4_A4_002 to print Routing info
//	@XmlEnumValue("ARCH_8X4_A4")
//  ARCH_8X4_A4_PDF("ARCH_8X4_A4"),
	@XmlEnumValue("ARCH_8X4_A4_002")
	ARCH_8X4_A4_PDF("ARCH_8X4_A4_002"),
    @XmlEnumValue("ARCH_8X4")
	ARCH_8X4_thermal("ARCH_8X4"),
//  @XmlEnumValue("ARCH_8X4_A4")
//	ARCH_8X4_A4_TC_PDF("ARCH_8X4_A4"),
	@XmlEnumValue("ARCH_8X4_A4_002")
	ARCH_8X4_A4_TC_PDF("ARCH_8X4_A4_002"),
	@XmlEnumValue("ARCH_6X4")
	ARCH_6X4_thermal("ARCH_6X4"),
    @XmlEnumValue("ARCH_6X4")
	ARCH_6X4_A4_PDF("ARCH_6X4"),
	@XmlEnumValue("ARCH_8X4")
	ARCH_8X4_CI_PDF("ARCH_8X4"),
	@XmlEnumValue("ARCH_8X4")
	ARCH_8X4_CI_thermal("ARCH_8X4"),
	//BEGIN :: Added below New value for XMLPI Label Enhancement :: Rajesh Nagampurath :: 08-DEC-2014 | XMLPI Label Enhancement | XML_PI_v52_Cyrillic
	/*@XmlEnumValue("RU_ARCH_A4")
	ARCH_8X4_RU_PDF("RU_ARCH_A4");*/
	@XmlEnumValue("ARCH_A4_RU_002")
	ARCH_8X4_RU_A4_PDF("ARCH_A4_RU_002"),
	@XmlEnumValue("ARCH_6X4")
	ARCH_6X4_PDF("ARCH_6X4"),	
	@XmlEnumValue("ARCH_8X4")
	ARCH_8X4_PDF("ARCH_8X4"),
	//END :: Rajesh Nagampurath :: 08-DEC-2014 | XMLPI Label Enhancement | XML_PI_v52_Cyrillic
	
	@XmlEnumValue("ARCH_8X4_A4_002")
    ARCH_8X4_CustBarCode_PDF("ARCH_8X4_A4_002"),
    @XmlEnumValue("ARCH_8X4")
    ARCH_8X4_CustBarCode_thermal("ARCH_8X4");
	
    private final String value;

    ArchiveLabelTemplate(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ArchiveLabelTemplate fromValue(String v) {
        for (ArchiveLabelTemplate c: ArchiveLabelTemplate.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
