//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:27 PM IST 
//


package com.dhl.xmlpi.labelservice.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Handling
 * 
 * <p>Java class for Handling complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Handling">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FeatureNum" type="{http://www.dhl.com/LabelService_datatypes}FeatureNum" minOccurs="0"/>
 *         &lt;element name="FeatureCode" type="{http://www.dhl.com/LabelService_datatypes}FeatureCode" minOccurs="0"/>
 *         &lt;element name="SortCode" type="{http://www.dhl.com/LabelService_datatypes}SortCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Handling", propOrder = {
    "featureNum",
    "featureCode",
    "sortCode"
})
public class Handling {

    @XmlElement(name = "FeatureNum")
    protected String featureNum;
    @XmlElement(name = "FeatureCode")
    protected FeatureCode featureCode;
    @XmlElement(name = "SortCode")
    protected String sortCode;

    /**
     * Gets the value of the featureNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureNum() {
        return featureNum;
    }

    /**
     * Sets the value of the featureNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureNum(String value) {
        this.featureNum = value;
    }

    /**
     * Gets the value of the featureCode property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureCode }
     *     
     */
    public FeatureCode getFeatureCode() {
        return featureCode;
    }

    /**
     * Sets the value of the featureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureCode }
     *     
     */
    public void setFeatureCode(FeatureCode value) {
        this.featureCode = value;
    }

    /**
     * Gets the value of the sortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortCode() {
        return sortCode;
    }

    /**
     * Sets the value of the sortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortCode(String value) {
        this.sortCode = value;
    }

}
