//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:27 PM IST 
//


package com.dhl.xmlpi.labelservice.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Label
 * 
 * <p>Java class for Label complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Label">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelLayout" type="{http://www.dhl.com/LabelService_datatypes}LabelLayout"/>
 *         &lt;element name="LabelTemplate" type="{http://www.dhl.com/LabelService_datatypes}LabelTemplate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Label", propOrder = {
    "labelLayout",
    "labelTemplate",
    "archiveLabelTemplate",
    "hideAccount",
    "customerBarcodeType",
    "customerBarcodeCode",
    "customerBarcodeText"
})
public class Label {

    @XmlElement(name = "LabelLayout", required = true)
    protected LabelLayout labelLayout;
    @XmlElement(name = "LabelTemplate")
    protected LabelTemplate labelTemplate;
    
    //BEGIN :: Pavan Kumar (TechMahindra) | 01-AUG-2013 | XMLPI 4.7 | Label Enhancement
    @XmlElement(name = "ArchiveLabelTemplate")
    protected ArchiveLabelTemplate archiveLabelTemplate;
    
    @XmlElement(name="HideAccount")
    protected String hideAccount;

    //Begin : Sathish | 23-Jan-2017|Added for XMLPI V6.0
    @XmlElement(name = "CustomerBarcodeType")
    protected String customerBarcodeType;

    @XmlElement(name = "CustomerBarcodeCode")
    protected String customerBarcodeCode;

    @XmlElement(name = "CustomerBarcodeText")
    protected String customerBarcodeText;
   //End : Sathish | 23-Jan-2017|Added for XMLPI V6.0
    
    /**
	 * @return the hideAccount
	 */
	public String getHideAccount() {
		return hideAccount;
	}

	/**
	 * @param hideAccount the hideAccount to set
	 */
	public void setHideAccount(String hideAccount) {
		this.hideAccount = hideAccount;
	}

    /**
	 * @return the archiveLabelTemplate
	 */
	public ArchiveLabelTemplate getArchiveLabelTemplate() {
		return archiveLabelTemplate;
	}

	/**
	 * @param archiveLabelTemplate the archiveLabelTemplate to set
	 */
	public void setArchiveLabelTemplate(ArchiveLabelTemplate archiveLabelTemplate) {
		this.archiveLabelTemplate = archiveLabelTemplate;
	}
	// END

	/**
     * Gets the value of the labelLayout property.
     * 
     * @return
     *     possible object is
     *     {@link LabelLayout }
     *     
     */
    public LabelLayout getLabelLayout() {
        return labelLayout;
    }

    /**
     * Sets the value of the labelLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelLayout }
     *     
     */
    public void setLabelLayout(LabelLayout value) {
        this.labelLayout = value;
    }

    /**
     * Gets the value of the labelTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link LabelTemplate }
     *     
     */
    public LabelTemplate getLabelTemplate() {
        return labelTemplate;
    }

    /**
     * Sets the value of the labelTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelTemplate }
     *     
     */
    public void setLabelTemplate(LabelTemplate value) {
        this.labelTemplate = value;
    }


	public String getCustomerBarcodeType() {
		return customerBarcodeType;
	}

	public void setCustomerBarcodeType(String customerBarcodeType) {
		this.customerBarcodeType = customerBarcodeType;
	}

	public String getCustomerBarcodeCode() {
		return customerBarcodeCode;
	}

	public void setCustomerBarcodeCode(String customerBarcodeCode) {
		this.customerBarcodeCode = customerBarcodeCode;
	}

	public String getCustomerBarcodeText() {
		return customerBarcodeText;
	}

	public void setCustomerBarcodeText(String customerBarcodeText) {
		this.customerBarcodeText = customerBarcodeText;
	}

}
