//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:27 PM IST 
//


package com.dhl.xmlpi.labelservice.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * LabelPrintCommands
 * 
 * <p>Java class for LabelPrintCommands complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LabelPrintCommands">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelPrintCommand" type="{http://www.dhl.com/LabelService_datatypes}LabelPrintCommand" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LabelPrintCommands", propOrder = {
    "labelPrintCommand"
})
public class LabelPrintCommands {

    @XmlElement(name = "LabelPrintCommand")
    protected byte[] labelPrintCommand;

    /**
     * Gets the value of the labelPrintCommand property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getLabelPrintCommand() {
        return labelPrintCommand;
    }

    /**
     * Sets the value of the labelPrintCommand property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setLabelPrintCommand(byte[] value) {
        this.labelPrintCommand = ((byte[]) value);
    }

}
