//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:27 PM IST 
//


package com.dhl.xmlpi.labelservice.model.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{http://www.dhl.com/LabelService_datatypes}Request"/>
 *         &lt;element name="LabelType" type="{http://www.dhl.com/LabelService_datatypes}LabelType"/>
 *         &lt;element name="AirwayBillNumber" type="{http://www.dhl.com/LabelService_datatypes}AirwayBillNumber"/>
 *         &lt;element name="DHLLogoFlag" type="{http://www.dhl.com/LabelService_datatypes}DHLLogoFlag"/>
 *         &lt;element name="LookUpFlag" type="{http://www.dhl.com/LabelService_datatypes}LookUpFlag"/>
 *         &lt;element name="AddrMapFlag" type="{http://www.dhl.com/LabelService_datatypes}AddrMapFlag"/>
 *         &lt;element name="CertID" type="{http://www.dhl.com/LabelService_datatypes}CertID" minOccurs="0"/>
 *         &lt;element name="CustomerLogo" type="{http://www.w3.org/LabelService_datatypes}CustomerLogo" minOccurs="0"
 *         &lt;element name="formDataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"
 *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"
 *         &lt;element name="labelTemplateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"
 *         &lt;element name="Labels" type="{http://www.dhl.com/LabelService_datatypes}Labels"/>
 *         &lt;element name="Origin" type="{http://www.dhl.com/LabelService_datatypes}Origin"/>
 *         &lt;element name="Destination" type="{http://www.dhl.com/LabelService_datatypes}Destination"/>
 *         &lt;element name="Shipment" type="{http://www.dhl.com/LabelService_datatypes}Shipment"/>
 *         &lt;element name="Pieces" type="{http://www.dhl.com/LabelService_datatypes}Pieces"/>
 *         &lt;element name="Services" type="{http://www.dhl.com/LabelService_datatypes}Services" minOccurs="0"/>
 *         &lt;element name="Handlings" type="{http://www.dhl.com/LabelService_datatypes}Handlings" minOccurs="0"/>
 *         &lt;element name="Filing" type="{http://www.dhl.com/LabelService_datatypes}Filing" minOccurs="0"/>
 *         &lt;element name="InsuredAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "labelType",
    "airwayBillNumber",
    "dhlLogoFlag",
    "lookUpFlag",
    "addrMapFlag",
    "certID",
    "customerLogo",
    "formDataType",
    "resolution",
    "labelTemplateType",
    "labels",
    "origin",
    "destination",
    "shipment",
    "pieces",
    "services",
    "handlings",
    "filing",
    "insuredAmount",
    "dangerousGoods"
})
@XmlRootElement(name = "LabelService", namespace = "http://www.dhl.com")
public class LabelService {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "LabelType", required = true)
    protected LabelType labelType;
    @XmlElement(name = "AirwayBillNumber", required = true)
    protected String airwayBillNumber;
    @XmlElement(name = "DHLLogoFlag", required = true)
    protected DHLLogoFlag dhlLogoFlag;
    @XmlElement(name = "LookUpFlag", required = true)
    protected LookUpFlag lookUpFlag;
    @XmlElement(name = "AddrMapFlag", required = true)
    protected AddrMapFlag addrMapFlag;
    @XmlElement(name = "CertID")
    protected String certID;
    @XmlElement(name = "Labels", required = true)
    protected Labels labels;
    @XmlElement(name = "Origin", required = true)
    protected Origin origin;
    @XmlElement(name = "Destination", required = true)
    protected Destination destination;
    @XmlElement(name = "Shipment", required = true)
    protected Shipment shipment;
    @XmlElement(name = "Pieces", required = true)
    protected Pieces pieces;
    @XmlElement(name = "Services")
    protected Services services;
    @XmlElement(name = "Handlings")
    protected Handlings handlings;
    @XmlElement(name = "Filing")
    protected Filing filing;
    @XmlElement(name = "InsuredAmount")
    protected String insuredAmount;
    @XmlElement(name = "DGs")
    protected DGs dangerousGoods;

    //BEGIN :: Pavan Kumar (TechMahindra) | 23-AUG-2013 | XMLPI 4.7 | HPQC 9
    @XmlElement(name = "FormDataType")
    protected String formDataType;
    
    /**
	 * @return the formDataType
	 */
	public String getFormDataType() {
		return formDataType;
	}

	/**
	 * @param formDataType the formDataType to set
	 */
	public void setFormDataType(String formDataType) {
		this.formDataType = formDataType;
	}
	// END

	//BEGIN :: Pavan Kumar (TechMahindra) | 05-AUG-2013 | XMLPI 4.7 | Label Enhancement
    @XmlElement(name = "CustomerLogo")
    protected CustomerLogo customerLogo;
    
    /**
	 * @return the customerLogo
	 */
	public CustomerLogo getCustomerLogo() {
		return customerLogo;
	}

	/**
	 * @param customerLogo the customerLogo to set
	 */
	public void setCustomerLogo(CustomerLogo customerLogo) {
		this.customerLogo = customerLogo;
	}
	//END

	//BEGIN :: Ravi Rastogi (MSAT) | 24-JUL-2013 | XMLPI 4.7 | Resolution option
    @XmlElement(name = "Resolution", required = true)
    protected String resolution;

    
	public String getResolution() {
		return resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}
	//END
	
	//BEGIN :: Pavan Kumar (TechMahindra) | 26-AUG-2013 | XMLPI 4.7 | Label Enhancement
    @XmlElement(name = "LabelTemplateType")
    protected String labelTemplateType;

	/**
	 * @return the labelTemplateType
	 */
	public String getLabelTemplateType() {
		return labelTemplateType;
	}

	/**
	 * @param labelTemplateType the labelTemplateType to set
	 */
	public void setLabelTemplateType(String labelTemplateType) {
		this.labelTemplateType = labelTemplateType;
	}
	//END

	/**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the labelType property.
     * 
     * @return
     *     possible object is
     *     {@link LabelType }
     *     
     */
    public LabelType getLabelType() {
        return labelType;
    }

    /**
     * Sets the value of the labelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelType }
     *     
     */
    public void setLabelType(LabelType value) {
        this.labelType = value;
    }

    /**
     * Gets the value of the airwayBillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwayBillNumber() {
        return airwayBillNumber;
    }

    /**
     * Sets the value of the airwayBillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwayBillNumber(String value) {
        this.airwayBillNumber = value;
    }

    /**
     * Gets the value of the dhlLogoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link DHLLogoFlag }
     *     
     */
    public DHLLogoFlag getDHLLogoFlag() {
        return dhlLogoFlag;
    }

    /**
     * Sets the value of the dhlLogoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link DHLLogoFlag }
     *     
     */
    public void setDHLLogoFlag(DHLLogoFlag value) {
        this.dhlLogoFlag = value;
    }

    /**
     * Gets the value of the lookUpFlag property.
     * 
     * @return
     *     possible object is
     *     {@link LookUpFlag }
     *     
     */
    public LookUpFlag getLookUpFlag() {
        return lookUpFlag;
    }

    /**
     * Sets the value of the lookUpFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookUpFlag }
     *     
     */
    public void setLookUpFlag(LookUpFlag value) {
        this.lookUpFlag = value;
    }

    /**
     * Gets the value of the addrMapFlag property.
     * 
     * @return
     *     possible object is
     *     {@link AddrMapFlag }
     *     
     */
    public AddrMapFlag getAddrMapFlag() {
        return addrMapFlag;
    }

    /**
     * Sets the value of the addrMapFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrMapFlag }
     *     
     */
    public void setAddrMapFlag(AddrMapFlag value) {
        this.addrMapFlag = value;
    }

    /**
     * Gets the value of the certID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertID() {
        return certID;
    }

    /**
     * Sets the value of the certID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertID(String value) {
        this.certID = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * @return
     *     possible object is
     *     {@link Labels }
     *     
     */
    public Labels getLabels() {
        return labels;
    }

    /**
     * Sets the value of the labels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Labels }
     *     
     */
    public void setLabels(Labels value) {
        this.labels = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Origin }
     *     
     */
    public Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origin }
     *     
     */
    public void setOrigin(Origin value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link Destination }
     *     
     */
    public Destination getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Destination }
     *     
     */
    public void setDestination(Destination value) {
        this.destination = value;
    }

    /**
     * Gets the value of the shipment property.
     * 
     * @return
     *     possible object is
     *     {@link Shipment }
     *     
     */
    public Shipment getShipment() {
        return shipment;
    }

    /**
     * Sets the value of the shipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipment }
     *     
     */
    public void setShipment(Shipment value) {
        this.shipment = value;
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return
     *     possible object is
     *     {@link Pieces }
     *     
     */
    public Pieces getPieces() {
        return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pieces }
     *     
     */
    public void setPieces(Pieces value) {
        this.pieces = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link Services }
     *     
     */
    public Services getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link Services }
     *     
     */
    public void setServices(Services value) {
        this.services = value;
    }

    /**
     * Gets the value of the handlings property.
     * 
     * @return
     *     possible object is
     *     {@link Handlings }
     *     
     */
    public Handlings getHandlings() {
        return handlings;
    }

    /**
     * Sets the value of the handlings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Handlings }
     *     
     */
    public void setHandlings(Handlings value) {
        this.handlings = value;
    }

    /**
     * Gets the value of the filing property.
     * 
     * @return
     *     possible object is
     *     {@link Filing }
     *     
     */
    public Filing getFiling() {
        return filing;
    }

    /**
     * Sets the value of the filing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filing }
     *     
     */
    public void setFiling(Filing value) {
        this.filing = value;
    }

    /**
     * Gets the value of the insuredAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredAmount() {
        return insuredAmount;
    }

    /**
     * Sets the value of the insuredAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredAmount(String value) {
        this.insuredAmount = value;
    }

	public DGs getDangerousGoods() {
		return dangerousGoods;
	}

	public void setDangerousGoods(DGs dangerousGoods) {
		this.dangerousGoods = dangerousGoods;
	}

}
