//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:27 PM IST 
//

//@javax.xml.bind.annotation.XmlSchema(namespace="http://www.dhl.com/LabelService_datatypes")
//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dhl.com/CommercialInvoice_datatypes")
@javax.xml.bind.annotation.XmlSchema(xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI = "http://www.dhl.com/LabelService_datatypes"),
		@javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI = "http://www.dhl.com/CommercialInvoice_datatypes") })
package com.dhl.xmlpi.labelservice.model.request;
