//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.25 at 02:04:03 PM IST 
//


package com.dhl;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.dhl.datatypes.BillCode;
import com.dhl.datatypes.Billing;
import com.dhl.datatypes.Consignee;
import com.dhl.datatypes.DestinationServiceArea;
import com.dhl.datatypes.Dutiable;
import com.dhl.datatypes.ExportDeclaration;
import com.dhl.datatypes.Note;
import com.dhl.datatypes.OriginServiceArea;
import com.dhl.datatypes.Reference;
import com.dhl.datatypes.Response;
import com.dhl.datatypes.ShipValResponsePieces;
import com.dhl.datatypes.Shipper;
import com.dhl.datatypes.SpecialService;
import com.dhl.datatypes.YesNo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response" type="{http://www.dhl.com/datatypes}Response"/>
 *         &lt;element name="Note" type="{http://www.dhl.com/datatypes}Note"/>
 *         &lt;element name="AirwayBillNumber" type="{http://www.dhl.com/datatypes}AWBNumber"/>
 *         &lt;element name="BillingCode" type="{http://www.dhl.com/datatypes}BillCode"/>
 *         &lt;element name="CurrencyCode" type="{http://www.dhl.com/datatypes}CurrencyCode"/>
 *         &lt;element name="CourierMessage" type="{http://www.dhl.com/datatypes}CourierMsg" minOccurs="0"/>
 *         &lt;element name="DHLRoutingCode" type="{http://www.dhl.com/datatypes}DHLRoutingCode" minOccurs="0"/>
 *         &lt;element name="DHLRoutingDataId" type="{http://www.dhl.com/datatypes}DHLRoutingCode" minOccurs="0"/>
 *         &lt;element name="DestinationServiceArea" type="{http://www.dhl.com/datatypes}DestinationServiceArea"/>
 *         &lt;element name="OriginServiceArea" type="{http://www.dhl.com/datatypes}OriginServiceArea"/>
 *         &lt;element name="ProductContentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InternalServiceCode" type="{http://www.dhl.com/datatypes}InternalServiceCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeliveryDateCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryTimeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Pieces" type="{http://www.dhl.com/datatypes}ShipValResponsePieces" minOccurs="0"/>
 *         &lt;element name="PackageCharge" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="Rated" type="{http://www.dhl.com/datatypes}YesNo"/>
 *         &lt;element name="ShippingCharge" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="ShippingChargeInUSD" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="WeightUnit" type="{http://www.dhl.com/datatypes}WeightUnit"/>
 *         &lt;element name="ChargeableWeight" type="{http://www.dhl.com/datatypes}Weight"/>
 *         &lt;element name="DimensionalWeight" type="{http://www.dhl.com/datatypes}Weight"/>
 *         &lt;element name="ReadyByTime" type="{http://www.dhl.com/datatypes}TimeHM" minOccurs="0"/>
 *         &lt;element name="PickupCharge" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="CallInTime" type="{http://www.dhl.com/datatypes}TimeHM" minOccurs="0"/>
 *         &lt;element name="DaysAdvanceNotice" type="{http://www.dhl.com/datatypes}AdvanceDaysNotice" minOccurs="0"/>
 *         &lt;element name="ConversionRate" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="CountryCode" type="{http://www.dhl.com/datatypes}CountryCode"/>
 *         &lt;element name="Barcodes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AWBBarCode" type="{http://www.dhl.com/datatypes}BarCode"/>
 *                   &lt;element name="OriginDestnBarcode" type="{http://www.dhl.com/datatypes}BarCode"/>
 *                   &lt;element name="ClientIDBarCode" type="{http://www.dhl.com/datatypes}BarCode" minOccurs="0"/>
 *                   &lt;element name="BarCode2D" type="{http://www.dhl.com/datatypes}BarCode" minOccurs="0"/>
 *                   &lt;element name="DHLRoutingBarCode" type="{http://www.dhl.com/datatypes}BarCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Piece" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Contents" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reference" type="{http://www.dhl.com/datatypes}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Consignee" type="{http://www.dhl.com/datatypes}Consignee"/>
 *         &lt;element name="Shipper" type="{http://www.dhl.com/datatypes}Shipper"/>
 *         &lt;element name="AccountNumber" type="{http://www.dhl.com/datatypes}AccountNumber" minOccurs="0"/>
 *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ShipmentDate" type="{http://www.dhl.com/datatypes}Date"/>
 *         &lt;element name="GlobalProductCode" type="{http://www.dhl.com/datatypes}ProductCode"/>
 *         &lt;element name="SpecialService" type="{http://www.dhl.com/datatypes}SpecialService" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="Billing" type="{http://www.dhl.com/datatypes}Billing" minOccurs="0"/>
 *         &lt;element name="Dutiable" type="{http://www.dhl.com/datatypes}Dutiable" minOccurs="0"/>
 *         &lt;element name="ExportDeclaration" type="{http://www.dhl.com/datatypes}ExportDeclaration" minOccurs="0"/>
 *         &lt;element name="NewShipper" type="{http://www.dhl.com/datatypes}YesNo" minOccurs="0"/>
 *         &lt;element name="InsuredAmount" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="SDeliveryDt" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EDeliveryDt" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LHPOrigCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LHPDestCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "note",
    "airwayBillNumber",
    "billingCode",
    "currencyCode",
    "courierMessage",
    "dhlRoutingCode",
    "dhlRoutingDataId",
    "destinationServiceArea",
    "originServiceArea",
    "productContentCode",
    "productShortName",
    "internalServiceCode",
    "deliveryDateCode",
    "deliveryTimeCode",
    "pieces",
    "packageCharge",
    "rated",
    "shippingCharge",
    "shippingChargeInUSD",
    "weightUnit",
    "chargeableWeight",
    "dimensionalWeight",
    "readyByTime",
    "pickupCharge",
    "callInTime",
    "daysAdvanceNotice",
    "conversionRate",
    "countryCode",
    "barcodes",
    "piece",
    "contents",
    "reference",
    "consignee",
    "shipper",
    "accountNumber",
    "customerID",
    "shipmentDate",
    "globalProductCode",
    "specialService",
    "billing",
    "dutiable",
    "exportDeclaration",
    "newShipper",
    "sDeliveryDt",
    "eDeliveryDt",
    "lhpOrigCd",
    "lhpDestCd",
    "insuredAmount"
})
@XmlRootElement(name = "ShipmentValidateResponse")
public class ShipmentValidateResponse {

    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElement(name = "Note", required = true)
    protected Note note;
    @XmlElement(name = "AirwayBillNumber", required = true)
    protected String airwayBillNumber;
    @XmlElement(name = "BillingCode", required = true)
    protected BillCode billingCode;
    @XmlElement(name = "CurrencyCode", required = true)
    protected String currencyCode;
    @XmlElement(name = "CourierMessage")
    protected String courierMessage;
    @XmlElement(name = "DHLRoutingCode")
    protected String dhlRoutingCode;
    @XmlElement(name = "DHLRoutingDataId")
    protected String dhlRoutingDataId;
    @XmlElement(name = "DestinationServiceArea", required = true)
    protected DestinationServiceArea destinationServiceArea;
    @XmlElement(name = "OriginServiceArea", required = true)
    protected OriginServiceArea originServiceArea;
    @XmlElement(name = "ProductContentCode")
    protected String productContentCode;
    @XmlElement(name = "ProductShortName")
    protected String productShortName;
    @XmlElement(name = "InternalServiceCode")
    protected List<String> internalServiceCode;
    @XmlElement(name = "DeliveryDateCode")
    protected String deliveryDateCode;
    @XmlElement(name = "DeliveryTimeCode")
    protected String deliveryTimeCode;
    @XmlElement(name = "Pieces")
    protected ShipValResponsePieces pieces;
    @XmlElement(name = "PackageCharge")
    protected Float packageCharge;
    @XmlElement(name = "Rated", required = true)
    protected YesNo rated;
    @XmlElement(name = "ShippingCharge")
    protected Float shippingCharge;
    @XmlElement(name = "ShippingChargeInUSD")
    protected Float shippingChargeInUSD;
    @XmlElement(name = "WeightUnit", required = true)
    protected String weightUnit;
    @XmlElement(name = "ChargeableWeight", required = true)
    protected BigDecimal chargeableWeight;
    @XmlElement(name = "DimensionalWeight", required = true)
    protected BigDecimal dimensionalWeight;
    @XmlElement(name = "ReadyByTime")
    protected XMLGregorianCalendar readyByTime;
    @XmlElement(name = "PickupCharge")
    protected Float pickupCharge;
    @XmlElement(name = "CallInTime")
    protected XMLGregorianCalendar callInTime;
    @XmlElement(name = "DaysAdvanceNotice")
    protected BigInteger daysAdvanceNotice;
    @XmlElement(name = "ConversionRate")
    protected Float conversionRate;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "Barcodes", required = true)
    protected ShipmentValidateResponse.Barcodes barcodes;
    @XmlElement(name = "Piece", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger piece;
    @XmlElement(name = "Contents")
    protected String contents;
    @XmlElement(name = "Reference")
    protected List<Reference> reference;
    @XmlElement(name = "Consignee", required = true)
    protected Consignee consignee;
    @XmlElement(name = "Shipper", required = true)
    protected Shipper shipper;
    @XmlElement(name = "AccountNumber")
    protected Long accountNumber;
    @XmlElement(name = "CustomerID", required = true)
    protected String customerID;
    @XmlElement(name = "ShipmentDate", required = true)
    protected XMLGregorianCalendar shipmentDate;
    @XmlElement(name = "GlobalProductCode", required = true)
    protected String globalProductCode;
    @XmlElement(name = "SpecialService")
    protected List<SpecialService> specialService;
    @XmlElement(name = "Billing")
    protected Billing billing;
    @XmlElement(name = "Dutiable")
    protected Dutiable dutiable;
    @XmlElement(name = "ExportDeclaration")
    protected ExportDeclaration exportDeclaration;
    @XmlElement(name = "NewShipper")
    protected YesNo newShipper;
    @XmlElement(name = "SDeliveryDt")
    protected String sDeliveryDt;
    @XmlElement(name = "EDeliveryDt")
    protected String eDeliveryDt;
    @XmlElement(name = "LHPOrigCd")
    protected String lhpOrigCd;
    @XmlElement(name = "LHPDestCd")
    protected String lhpDestCd;
    @XmlElement(name = "InsuredAmount")
    protected Float insuredAmount;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Note }
     *     
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Note }
     *     
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the airwayBillNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwayBillNumber() {
        return airwayBillNumber;
    }

    /**
     * Sets the value of the airwayBillNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwayBillNumber(String value) {
        this.airwayBillNumber = value;
    }

    /**
     * Gets the value of the billingCode property.
     * 
     * @return
     *     possible object is
     *     {@link BillCode }
     *     
     */
    public BillCode getBillingCode() {
        return billingCode;
    }

    /**
     * Sets the value of the billingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillCode }
     *     
     */
    public void setBillingCode(BillCode value) {
        this.billingCode = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the courierMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourierMessage() {
        return courierMessage;
    }

    /**
     * Sets the value of the courierMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourierMessage(String value) {
        this.courierMessage = value;
    }

    /**
     * Gets the value of the dhlRoutingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDHLRoutingCode() {
        return dhlRoutingCode;
    }

    /**
     * Sets the value of the dhlRoutingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDHLRoutingCode(String value) {
        this.dhlRoutingCode = value;
    }

    /**
     * Gets the value of the dhlRoutingDataId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDHLRoutingDataId() {
        return dhlRoutingDataId;
    }

    /**
     * Sets the value of the dhlRoutingDataId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDHLRoutingDataId(String value) {
        this.dhlRoutingDataId = value;
    }

    /**
     * Gets the value of the destinationServiceArea property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationServiceArea }
     *     
     */
    public DestinationServiceArea getDestinationServiceArea() {
        return destinationServiceArea;
    }

    /**
     * Sets the value of the destinationServiceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationServiceArea }
     *     
     */
    public void setDestinationServiceArea(DestinationServiceArea value) {
        this.destinationServiceArea = value;
    }

    /**
     * Gets the value of the originServiceArea property.
     * 
     * @return
     *     possible object is
     *     {@link OriginServiceArea }
     *     
     */
    public OriginServiceArea getOriginServiceArea() {
        return originServiceArea;
    }

    /**
     * Sets the value of the originServiceArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginServiceArea }
     *     
     */
    public void setOriginServiceArea(OriginServiceArea value) {
        this.originServiceArea = value;
    }

    /**
     * Gets the value of the productContentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductContentCode() {
        return productContentCode;
    }

    /**
     * Sets the value of the productContentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductContentCode(String value) {
        this.productContentCode = value;
    }

    /**
     * Gets the value of the productShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductShortName() {
        return productShortName;
    }

    /**
     * Sets the value of the productShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductShortName(String value) {
        this.productShortName = value;
    }

    /**
     * Gets the value of the internalServiceCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internalServiceCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternalServiceCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInternalServiceCode() {
        if (internalServiceCode == null) {
            internalServiceCode = new ArrayList<String>();
        }
        return this.internalServiceCode;
    }

    /**
     * Gets the value of the deliveryDateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDateCode() {
        return deliveryDateCode;
    }

    /**
     * Sets the value of the deliveryDateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDateCode(String value) {
        this.deliveryDateCode = value;
    }

    /**
     * Gets the value of the deliveryTimeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTimeCode() {
        return deliveryTimeCode;
    }

    /**
     * Sets the value of the deliveryTimeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTimeCode(String value) {
        this.deliveryTimeCode = value;
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return
     *     possible object is
     *     {@link ShipValResponsePieces }
     *     
     */
    public ShipValResponsePieces getPieces() {
        return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipValResponsePieces }
     *     
     */
    public void setPieces(ShipValResponsePieces value) {
        this.pieces = value;
    }

    /**
     * Gets the value of the packageCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPackageCharge() {
        return packageCharge;
    }

    /**
     * Sets the value of the packageCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPackageCharge(Float value) {
        this.packageCharge = value;
    }

    /**
     * Gets the value of the rated property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getRated() {
        return rated;
    }

    /**
     * Sets the value of the rated property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setRated(YesNo value) {
        this.rated = value;
    }

    /**
     * Gets the value of the shippingCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getShippingCharge() {
        return shippingCharge;
    }

    /**
     * Sets the value of the shippingCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setShippingCharge(Float value) {
        this.shippingCharge = value;
    }

    /**
     * Gets the value of the shippingChargeInUSD property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getShippingChargeInUSD() {
        return shippingChargeInUSD;
    }

    /**
     * Sets the value of the shippingChargeInUSD property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setShippingChargeInUSD(Float value) {
        this.shippingChargeInUSD = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightUnit() {
        return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightUnit(String value) {
        this.weightUnit = value;
    }

    /**
     * Gets the value of the chargeableWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeableWeight() {
        return chargeableWeight;
    }

    /**
     * Sets the value of the chargeableWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeableWeight(BigDecimal value) {
        this.chargeableWeight = value;
    }

    /**
     * Gets the value of the dimensionalWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDimensionalWeight() {
        return dimensionalWeight;
    }

    /**
     * Sets the value of the dimensionalWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDimensionalWeight(BigDecimal value) {
        this.dimensionalWeight = value;
    }

    /**
     * Gets the value of the readyByTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReadyByTime() {
        return readyByTime;
    }

    /**
     * Sets the value of the readyByTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReadyByTime(XMLGregorianCalendar value) {
        this.readyByTime = value;
    }

    /**
     * Gets the value of the pickupCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPickupCharge() {
        return pickupCharge;
    }

    /**
     * Sets the value of the pickupCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPickupCharge(Float value) {
        this.pickupCharge = value;
    }

    /**
     * Gets the value of the callInTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCallInTime() {
        return callInTime;
    }

    /**
     * Sets the value of the callInTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCallInTime(XMLGregorianCalendar value) {
        this.callInTime = value;
    }

    /**
     * Gets the value of the daysAdvanceNotice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDaysAdvanceNotice() {
        return daysAdvanceNotice;
    }

    /**
     * Sets the value of the daysAdvanceNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDaysAdvanceNotice(BigInteger value) {
        this.daysAdvanceNotice = value;
    }

    /**
     * Gets the value of the conversionRate property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getConversionRate() {
        return conversionRate;
    }

    /**
     * Sets the value of the conversionRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setConversionRate(Float value) {
        this.conversionRate = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the barcodes property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentValidateResponse.Barcodes }
     *     
     */
    public ShipmentValidateResponse.Barcodes getBarcodes() {
        return barcodes;
    }

    /**
     * Sets the value of the barcodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentValidateResponse.Barcodes }
     *     
     */
    public void setBarcodes(ShipmentValidateResponse.Barcodes value) {
        this.barcodes = value;
    }

    /**
     * Gets the value of the piece property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPiece() {
        return piece;
    }

    /**
     * Sets the value of the piece property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPiece(BigInteger value) {
        this.piece = value;
    }

    /**
     * Gets the value of the contents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContents() {
        return contents;
    }

    /**
     * Sets the value of the contents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContents(String value) {
        this.contents = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getReference() {
        if (reference == null) {
            reference = new ArrayList<Reference>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link Consignee }
     *     
     */
    public Consignee getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consignee }
     *     
     */
    public void setConsignee(Consignee value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link Shipper }
     *     
     */
    public Shipper getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipper }
     *     
     */
    public void setShipper(Shipper value) {
        this.shipper = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountNumber(Long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the shipmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getShipmentDate() {
        return shipmentDate;
    }

    /**
     * Sets the value of the shipmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setShipmentDate(XMLGregorianCalendar value) {
        this.shipmentDate = value;
    }

    /**
     * Gets the value of the globalProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalProductCode() {
        return globalProductCode;
    }

    /**
     * Sets the value of the globalProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalProductCode(String value) {
        this.globalProductCode = value;
    }

    /**
     * Gets the value of the specialService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialService }
     * 
     * 
     */
    public List<SpecialService> getSpecialService() {
        if (specialService == null) {
            specialService = new ArrayList<SpecialService>();
        }
        return this.specialService;
    }

    /**
     * Gets the value of the billing property.
     * 
     * @return
     *     possible object is
     *     {@link Billing }
     *     
     */
    public Billing getBilling() {
        return billing;
    }

    /**
     * Sets the value of the billing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Billing }
     *     
     */
    public void setBilling(Billing value) {
        this.billing = value;
    }

    /**
     * Gets the value of the dutiable property.
     * 
     * @return
     *     possible object is
     *     {@link Dutiable }
     *     
     */
    public Dutiable getDutiable() {
        return dutiable;
    }

    /**
     * Sets the value of the dutiable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dutiable }
     *     
     */
    public void setDutiable(Dutiable value) {
        this.dutiable = value;
    }

    /**
     * Gets the value of the exportDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link ExportDeclaration }
     *     
     */
    public ExportDeclaration getExportDeclaration() {
        return exportDeclaration;
    }

    /**
     * Sets the value of the exportDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportDeclaration }
     *     
     */
    public void setExportDeclaration(ExportDeclaration value) {
        this.exportDeclaration = value;
    }

    /**
     * Gets the value of the newShipper property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getNewShipper() {
        return newShipper;
    }

    /**
     * Sets the value of the newShipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setNewShipper(YesNo value) {
        this.newShipper = value;
    }

    /**
     * Gets the value of the sDeliveryDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDeliveryDt() {
        return sDeliveryDt;
    }

    /**
     * Sets the value of the sDeliveryDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDeliveryDt(String value) {
        this.sDeliveryDt = value;
    }

    /**
     * Gets the value of the eDeliveryDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEDeliveryDt() {
        return eDeliveryDt;
    }

    /**
     * Sets the value of the eDeliveryDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEDeliveryDt(String value) {
        this.eDeliveryDt = value;
    }

    /**
     * Gets the value of the lhpOrigCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLHPOrigCd() {
        return lhpOrigCd;
    }

    /**
     * Sets the value of the lhpOrigCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLHPOrigCd(String value) {
        this.lhpOrigCd = value;
    }

    /**
     * Gets the value of the lhpDestCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLHPDestCd() {
        return lhpDestCd;
    }

    /**
     * Sets the value of the lhpDestCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLHPDestCd(String value) {
        this.lhpDestCd = value;
    }
    /**
     * Gets the value of the packageCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInsuredAmount() {
        return insuredAmount;
    }

    /**
     * Sets the value of the packageCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInsuredAmount(Float value) {
        this.insuredAmount = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AWBBarCode" type="{http://www.dhl.com/datatypes}BarCode"/>
     *         &lt;element name="OriginDestnBarcode" type="{http://www.dhl.com/datatypes}BarCode"/>
     *         &lt;element name="ClientIDBarCode" type="{http://www.dhl.com/datatypes}BarCode" minOccurs="0"/>
     *         &lt;element name="BarCode2D" type="{http://www.dhl.com/datatypes}BarCode" minOccurs="0"/>
     *         &lt;element name="DHLRoutingBarCode" type="{http://www.dhl.com/datatypes}BarCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "awbBarCode",
        "originDestnBarcode",
        "clientIDBarCode",
        "barCode2D",
        "dhlRoutingBarCode"
    })
    public static class Barcodes {

        @XmlElement(name = "AWBBarCode", required = true)
        protected byte[] awbBarCode;
        @XmlElement(name = "OriginDestnBarcode", required = true)
        protected byte[] originDestnBarcode;
        @XmlElement(name = "ClientIDBarCode")
        protected byte[] clientIDBarCode;
        @XmlElement(name = "BarCode2D")
        protected byte[] barCode2D;
        @XmlElement(name = "DHLRoutingBarCode")
        protected byte[] dhlRoutingBarCode;

        /**
         * Gets the value of the awbBarCode property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getAWBBarCode() {
            return awbBarCode;
        }

        /**
         * Sets the value of the awbBarCode property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setAWBBarCode(byte[] value) {
            this.awbBarCode = ((byte[]) value);
        }

        /**
         * Gets the value of the originDestnBarcode property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getOriginDestnBarcode() {
            return originDestnBarcode;
        }

        /**
         * Sets the value of the originDestnBarcode property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setOriginDestnBarcode(byte[] value) {
            this.originDestnBarcode = ((byte[]) value);
        }

        /**
         * Gets the value of the clientIDBarCode property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getClientIDBarCode() {
            return clientIDBarCode;
        }

        /**
         * Sets the value of the clientIDBarCode property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setClientIDBarCode(byte[] value) {
            this.clientIDBarCode = ((byte[]) value);
        }

        /**
         * Gets the value of the barCode2D property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getBarCode2D() {
            return barCode2D;
        }

        /**
         * Sets the value of the barCode2D property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setBarCode2D(byte[] value) {
            this.barCode2D = ((byte[]) value);
        }

        /**
         * Gets the value of the dhlRoutingBarCode property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getDHLRoutingBarCode() {
            return dhlRoutingBarCode;
        }

        /**
         * Sets the value of the dhlRoutingBarCode property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setDHLRoutingBarCode(byte[] value) {
            this.dhlRoutingBarCode = ((byte[]) value);
        }

    }

}
