//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 04:46:28 PM IST 
//


package com.dhl.xmlpi.labelservice.model.datatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Address Map
 * 
 * <p>Java class for AddrMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddrMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AddrLine1" type="{http://www.dhl.com/LabelService_datatypes}AddrLine1" minOccurs="0"/>
 *         &lt;element name="AddrLine2" type="{http://www.dhl.com/LabelService_datatypes}AddrLine2" minOccurs="0"/>
 *         &lt;element name="AddrLine3" type="{http://www.dhl.com/LabelService_datatypes}AddrLine3" minOccurs="0"/>
 *         &lt;element name="AptNoName" type="{http://www.dhl.com/LabelService_datatypes}AptNoName" minOccurs="0"/>
 *         &lt;element name="BuildingName" type="{http://www.dhl.com/LabelService_datatypes}BuildingName" minOccurs="0"/>
 *         &lt;element name="StreetName" type="{http://www.dhl.com/LabelService_datatypes}StreetName" minOccurs="0"/>
 *         &lt;element name="StreetNo" type="{http://www.dhl.com/LabelService_datatypes}StreetNo" minOccurs="0"/>
 *         &lt;element name="Province" type="{http://www.dhl.com/LabelService_datatypes}Province" minOccurs="0"/>
 *         &lt;element name="POBoxNo" type="{http://www.dhl.com/LabelService_datatypes}POBoxNo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddrMap", propOrder = {
    "addrLine1",
    "addrLine2",
    "addrLine3",
    "aptNoName",
    "buildingName",
    "streetName",
    "streetNo",
    "province",
    "poBoxNo"
})
public class AddrMap {

    @XmlElement(name = "AddrLine1")
    protected String addrLine1;
    @XmlElement(name = "AddrLine2")
    protected String addrLine2;
    @XmlElement(name = "AddrLine3")
    protected String addrLine3;
    @XmlElement(name = "AptNoName")
    protected String aptNoName;
    @XmlElement(name = "BuildingName")
    protected String buildingName;
    @XmlElement(name = "StreetName")
    protected String streetName;
    @XmlElement(name = "StreetNo")
    protected String streetNo;
    @XmlElement(name = "Province")
    protected String province;
    @XmlElement(name = "POBoxNo")
    protected String poBoxNo;

    /**
     * Gets the value of the addrLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLine1() {
        return addrLine1;
    }

    /**
     * Sets the value of the addrLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLine1(String value) {
        this.addrLine1 = value;
    }

    /**
     * Gets the value of the addrLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLine2() {
        return addrLine2;
    }

    /**
     * Sets the value of the addrLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLine2(String value) {
        this.addrLine2 = value;
    }

    /**
     * Gets the value of the addrLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLine3() {
        return addrLine3;
    }

    /**
     * Sets the value of the addrLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLine3(String value) {
        this.addrLine3 = value;
    }

    /**
     * Gets the value of the aptNoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAptNoName() {
        return aptNoName;
    }

    /**
     * Sets the value of the aptNoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAptNoName(String value) {
        this.aptNoName = value;
    }

    /**
     * Gets the value of the buildingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * Sets the value of the buildingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingName(String value) {
        this.buildingName = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNo() {
        return streetNo;
    }

    /**
     * Sets the value of the streetNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNo(String value) {
        this.streetNo = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvince(String value) {
        this.province = value;
    }

    /**
     * Gets the value of the poBoxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOBoxNo() {
        return poBoxNo;
    }

    /**
     * Sets the value of the poBoxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOBoxNo(String value) {
        this.poBoxNo = value;
    }

}
