//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.14 at 12:04:40 PM IST 
//


package com.dhl.xmlpi.labelservice.errorresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Label
 * 
 * <p>Java class for Label complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Label">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelLayout" type="{http://www.dhl.com/LabelService_datatypes}LabelLayout"/>
 *         &lt;element name="LabelTemplate" type="{http://www.dhl.com/LabelService_datatypes}LabelTemplate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Label", propOrder = {
    "labelLayout",
    "labelTemplate"
})
public class Label {

    @XmlElement(name = "LabelLayout", required = true)
    protected LabelLayout labelLayout;
    @XmlElement(name = "LabelTemplate", required = true)
    protected LabelTemplate labelTemplate;

    /**
     * Gets the value of the labelLayout property.
     * 
     * @return
     *     possible object is
     *     {@link LabelLayout }
     *     
     */
    public LabelLayout getLabelLayout() {
        return labelLayout;
    }

    /**
     * Sets the value of the labelLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelLayout }
     *     
     */
    public void setLabelLayout(LabelLayout value) {
        this.labelLayout = value;
    }

    /**
     * Gets the value of the labelTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link LabelTemplate }
     *     
     */
    public LabelTemplate getLabelTemplate() {
        return labelTemplate;
    }

    /**
     * Sets the value of the labelTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelTemplate }
     *     
     */
    public void setLabelTemplate(LabelTemplate value) {
        this.labelTemplate = value;
    }

}
