//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.14 at 12:04:40 PM IST 
//


package com.dhl.xmlpi.labelservice.errorresponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LabelTemplate.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LabelTemplate">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="30"/>
 *     &lt;enumeration value="ECOM26_84_001"/>
 *     &lt;enumeration value="ECOM26_84CI_001"/>
 *     &lt;enumeration value="ECOM26_A6_001"/>
 *     &lt;enumeration value="ECOM26_A4_001"/>
 *     &lt;enumeration value="ARCH_8X4"/>
 *     &lt;enumeration value="ECOM_A4_RU_002"/>
 *     &lt;enumeration value="ARCH_A4_RU_002"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LabelTemplate")
@XmlEnum
public enum LabelTemplate {

    @XmlEnumValue("ECOM26_84_001")
    ECOM_26_84_001("ECOM26_84_001"),
    @XmlEnumValue("ECOM26_84CI_001")
    ECOM_26_84_CI_001("ECOM26_84CI_001"),
    @XmlEnumValue("ECOM26_A6_001")
    ECOM_26_A_6_001("ECOM26_A6_001"),
    @XmlEnumValue("ECOM26_A4_001")
    ECOM_26_A_4_001("ECOM26_A4_001"),
    @XmlEnumValue("ARCH_8X4")
    ARCH_8_X_4("ARCH_8X4"),
    //BEGIN :: Added below New value for XMLPI Label Enhancement :: Rajesh Nagampurath :: 08-DEC-2014 | XMLPI Label Enhancement | XML_PI_v52_Cyrillic
    /*@XmlEnumValue("RU_ECOM_A4")
    RU_ECOM_A4("RU_ECOM_A4"),
    @XmlEnumValue("RU_ARCH_A4")
    RU_ARCH_A4("RU_ARCH_A4");*/
    @XmlEnumValue("ECOM_A4_RU_002")
    ECOM_A4_RU_002("ECOM_A4_RU_002"),
    @XmlEnumValue("ARCH_A4_RU_002")
    ARCH_A4_RU_002("ARCH_A4_RU_002");
    //END :: Rajesh Nagampurath :: 08-DEC-2014 | XMLPI Label Enhancement | XML_PI_v52_Cyrillic
    
    private final String value;

    LabelTemplate(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LabelTemplate fromValue(String v) {
        for (LabelTemplate c: LabelTemplate.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
